# docker-compose.yml

services:
  # Defines the backend service for your Django application.
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      # Syncs your local backend code with the container.
      - ./backend:/app

  # Defines the frontend service for your Next.js application.
  frontend:
    build: ./Frontend/my-app
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      # Syncs your local source code into the container.
      - ./Frontend/my-app:/app
      # The next two lines are the fix. They use Docker-managed volumes
      # for these specific subfolders to solve file permission errors.
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
